---
# tasks file for app

- name: git
  apt:
    name: git
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: clone project
  git:
    repo: https://github.com/brutalhz/deus2.git
    dest: "{{ project_dir }}"
    force: yes
  when: inventory_hostname in groups['app']

- name: copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ project_dir }}/docker-compose.yml"

- name: run docker compose up
  command: "docker-compose up -d"
  args:
    chdir: "{{ project_dir }}"
 
