---
# tasks file for docker
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items: "{{ packages }}"

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Add remote "vagrant" user to "docker" group
  remote_user: vagrant
  user:
    name: "vagrant"
    group: "docker"
    append: yes
  tags:
    - docker

- name: Install docker-compose
  remote_user: vagrant
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Delete docker containers
  shell: "docker rm -vf $(docker ps -aq) || true"
    
- name: Delete docker images
  shell: "docker rmi -f $(docker images -aq) || true"
